### ISSUE TITLE
Parse doubt

### ISSUE THREAD

**Issue by yzaguirre** [ruiquelhas/burton#2]
Should `parse` be set to `false`?
[see line 21](https://github.com/ruiquelhas/burton/blob/master/lib/index.js#L21)

**Comment by ruiquelhas** [comment]
Indeed. It makes sense to keep the payload intact after the validation. I'll give it a look.

Thanks.

**Comment by ruiquelhas** [comment]
Do you have any specific issue with the way it currently works? You see any use-case where it can be a problem?

I thought a bit about the implications of making the change, and they are somewhat overwhelming. Underneath the hood the work is delegated to [thurston](https://github.com/ruiquelhas/thurston) which requires `parse` to be `true`, which is indeed a requirement for route-level payload validation on [hapi](https://github.com/hapijs/hapi), and that means it might be the most sane thing to do.

**Comment by yzaguirre** [comment]
I was using multiparty to manage the uploaded file.
But gave me trouble when I applied burton validation. Even when both use the same payload configuration:

``` javascript
payload: {
        output: 'stream',
        parse: false
      }
```

So I skim-read burtons code, and thought line 21 was culprit. But it might not be the case.

**Comment by ruiquelhas** [comment]
What kind of trouble? Can you post some code? Keep in mind that `burton` only works for that specific configuration you mentioned. If `output` is not `stream` or parse is not `false`, the validation will be skipped.

**Comment by yzaguirre** [comment]
Thanks for your time. I've dug deeper into the multiparty exception and found the problem.

Multiparty depends on the request object specific structure. The following is multiparty working without validation:

``` javascript
exports.pictureUpload = function(request, reply){
  var form = new multiparty.Form();
  form.parse(request.payload, function(err, fields, files) {
[...]
```

Inside the parse function, it reads from the `request.payload.headers` attribute.

When Burton is activated, the request object is not the same. "headers" is missing, causing multiparty to crash. I found "headers" in `request` itself rather then in `request.payload.headers`. Problem solved, until multiparty wants to read the next function attribute: `request.pipe` but currently  in `request.payload.[fileKey].pipe`.

I guess burton (or multiparty) doesn't fit well with my setup.

**Comment by ruiquelhas** [comment]
Ok, that makes sense, and is in fact related to the line you mentioned.

Since the payload is already parsed when it arrives to your handler, the `headers` property is no longer there, which might not make too much sense on `burton`'s end. Thus, I would be willing to change that, but I'm looking for cleaner way to do it, maybe using an extension to restore the original payload before the handler gets called (which is not that great by itself).

However, I'm a bit curious why you are even using `multiparty` if `hapi` can already parse the payload data automatically for you. Can you elaborate a bit on that? I'm just trying to understand if the change would be worth the trouble.

Thanks.

**Comment by yzaguirre** [comment]
You're right, hapi already gives me everything. No need for multiparty, so I got rid of it. I'm closing the issue as it is resolved, thanks for your help.
